config/routes.rb
Rails.application.routes.draw do
  resources :compartments
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compartment.rb
class Compartment < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/compartments_controller.rb
class CompartmentsController < ApplicationController
  before_action :set_compartment, only: [:show, :edit, :update, :destroy]

  # GET /compartments
  # GET /compartments.json
  def index
    @compartments = Compartment.all
  end

  # GET /compartments/1
  # GET /compartments/1.json
  def show
  end

  # GET /compartments/new
  def new
    @compartment = Compartment.new
  end

  # GET /compartments/1/edit
  def edit
  end

  # POST /compartments
  # POST /compartments.json
  def create
    @compartment = Compartment.new(compartment_params)

    respond_to do |format|
      if @compartment.save
        format.html { redirect_to @compartment, notice: 'Compartment was successfully created.' }
        format.json { render :show, status: :created, location: @compartment }
      else
        format.html { render :new }
        format.json { render json: @compartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compartments/1
  # PATCH/PUT /compartments/1.json
  def update
    respond_to do |format|
      if @compartment.update(compartment_params)
        format.html { redirect_to @compartment, notice: 'Compartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @compartment }
      else
        format.html { render :edit }
        format.json { render json: @compartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compartments/1
  # DELETE /compartments/1.json
  def destroy
    @compartment.destroy
    respond_to do |format|
      format.html { redirect_to compartments_url, notice: 'Compartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compartment
      @compartment = Compartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compartment_params
      params.require(:compartment).permit(:name, :number, :shelf, :comment)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :placement, :count, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compartments_helper.rb
module CompartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/compartments/_form.html.erb
<%= form_with(model: compartment, local: true) do |form| %>
  <% if compartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compartment.errors.count, "error") %> prohibited this compartment from being saved:</h2>

      <ul>
      <% compartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :shelf %>
    <%= form.number_field :shelf %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/compartments/edit.html.erb
<h1>Editing Compartment</h1>

<%= render 'form', compartment: @compartment %>

<%= link_to 'Show', @compartment %> |
<%= link_to 'Back', compartments_path %>

app/views/compartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compartments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Shelf</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compartments.each do |compartment| %>
      <tr>
        <td><%= compartment.name %></td>
        <td><%= compartment.number %></td>
        <td><%= compartment.shelf %></td>
        <td><%= compartment.comment %></td>
        <td><%= link_to 'Show', compartment %></td>
        <td><%= link_to 'Edit', edit_compartment_path(compartment) %></td>
        <td><%= link_to 'Destroy', compartment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compartment', new_compartment_path %>

app/views/compartments/new.html.erb
<h1>New Compartment</h1>

<%= render 'form', compartment: @compartment %>

<%= link_to 'Back', compartments_path %>

app/views/compartments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @compartment.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @compartment.number %>
</p>

<p>
  <strong>Shelf:</strong>
  <%= @compartment.shelf %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @compartment.comment %>
</p>

<%= link_to 'Edit', edit_compartment_path(@compartment) %> |
<%= link_to 'Back', compartments_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :placement %>
    <%= form.number_field :placement %>
  </div>

  <div class="field">
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Placement</th>
      <th>Count</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.placement %></td>
        <td><%= item.count %></td>
        <td><%= item.comment %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Placement:</strong>
  <%= @item.placement %>
</p>

<p>
  <strong>Count:</strong>
  <%= @item.count %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @item.comment %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WhatWhere</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>